Karakoç/Models/Calisan.cs
using System;
using System.Collections.Generic;

namespace Karakoç.Models
{
    public partial class Calisan
    {
        public Calisan()
        {
            Giderlers = new HashSet<Giderler>();
            Mesais = new HashSet<Mesai>();
            Odemelers = new HashSet<Odemeler>();
            Yevmiyelers = new HashSet<Yevmiyeler>();
        }

        public int CalısanId { get; set; }
        public string Name { get; set; } = null!;
        public string Surname { get; set; } = null!;
        public DateTime? KayıtTarihi { get; set; }
        public string Email { get; set; } = null!;
        public string Password { get; set; } = null!;
        public long? TcKimlik { get; set; }
        public DateTime? BirthDate { get; set; }
        public byte? Authority { get; set; }
        public bool? Verify { get; set; }

        public virtual ICollection<Giderler> Giderlers { get; set; }
        public virtual ICollection<Mesai> Mesais { get; set; }
        public virtual ICollection<Odemeler> Odemelers { get; set; }
        public virtual ICollection<Yevmiyeler> Yevmiyelers { get; set; }
    }
}

Karakoç/Controllers/CalisanController.cs
using Karakoç.Bussiness.concrete;
using Karakoç.Models; 
using Microsoft.AspNetCore.Mvc;

namespace Karakoç.Controllers
{
    public class CalisanController : Controller
    {
        private readonly ResulContext _resulContext;
        private readonly CalisanManager manager;
        public CalisanController(CalisanManager calisanManager, ResulContext resulContext)
        {
            manager = calisanManager;
            _resulContext = resulContext;
        }

        [HttpGet]
        public IActionResult AnaSayfa()
        {
            if (!Control())
            {
                return RedirectToAction("Giris", "Login");
            }

            return View(manager.GetYevmiye(HttpContext)); // burası bir liste döndürücek geriye
        }

        public IActionResult Home()
        {
            if (!Control())
            {
                return RedirectToAction("Giris", "Login");
            }

            var CalisanId = Convert.ToInt32(HttpContext.Request.Cookies["CalisanId"]);
            var userName = HttpContext.Request.Cookies["UserName"];
            var userSurName = HttpContext.Request.Cookies["UserSurName"];
            var userEmail = HttpContext.Request.Cookies["UserEmail"];
            var KayitTarihi = HttpContext.Request.Cookies["KayitTarihi"];

            

            ViewBag.UserName = userName;
            ViewBag.UserSurName = userSurName;
            ViewBag.UserEmail = userEmail;
            ViewBag.KayitTarihi = KayitTarihi;

            var yevmiyeListesi = _resulContext.Yevmiyelers.Where(y => y.CalisanId == CalisanId).ToList();
            var mesaiListesi = _resulContext.Mesais.Where(y => y.CalisanId == CalisanId).ToList();
            var avansListesi = _resulContext.Odemelers.Where(y => y.CalisanId == CalisanId && y.Tarih.Month == DateTime.Now.Month).ToList();
            // Çalışılan günleri sayma
            double calismaGunSayisi = yevmiyeListesi.Count(y => y.IsWorked == true && y.Tarih.Value.Month == DateTime.Now.Month);
            double calismaYarimSayisi = yevmiyeListesi.Count(y => y.IsHalfWorked == true && y.Tarih.Value.Month == DateTime.Now.Month);
            double mesaiGunSayisi = mesaiListesi.Count(y => y.IsWorked == true && y.Tarih.Month == DateTime.Now.Month);
            double miktar = avansListesi.Sum(y => y.Amount);
            ViewBag.WorkedDays = calismaGunSayisi + (calismaYarimSayisi/2);
            mesaiGunSayisi = mesaiGunSayisi / 2;
            ViewBag.WorkedDaysMesai = mesaiGunSayisi;
            ViewBag.Total = calismaGunSayisi+ mesaiGunSayisi + (calismaYarimSayisi / 2);
            ViewBag.Miktar = miktar;
            ViewBag.UserName = userName+" "+userSurName;

            return View();
        }

        public IActionResult Puantajım()
        {
            if (!Control())
            {
                return RedirectToAction("Giris", "Login");
            }

            var kullaniciId = Convert.ToInt32(HttpContext.Request.Cookies["CalisanId"]);
            

            // Veritabanından bu kullanıcıya ait yevmiye kayıtlarını çek
            var yevmiyeKayitlari = _resulContext.Yevmiyelers
                .Where(y => y.CalisanId == kullaniciId)
                .ToList();

            return View(yevmiyeKayitlari);
        }

        [HttpGet("/Calisan/GetMyPuantaj")]
        public IActionResult GetMyPuantaj()
        {
            var CalisanId = Convert.ToInt32(HttpContext.Request.Cookies["CalisanId"]);
            
            var list = _resulContext.Yevmiyelers.Where(x => x.CalisanId == CalisanId).ToList();

            return  Json(list);
        }


        [HttpGet]
        public IActionResult Mesailerim()
        {
            if (!Control())
            {
                return RedirectToAction("Giris", "Login");
            }

            var kullaniciId = Convert.ToInt32(HttpContext.Request.Cookies["CalisanId"]);


            // Veritabanından bu kullanıcıya ait yevmiye kayıtlarını çek
            var yevmiyeKayitlari = _resulContext.Mesais
                .Where(y => y.CalisanId == kullaniciId)
                .ToList();

            return View(yevmiyeKayitlari);
            
        }

        [HttpGet("/Calisan/GetMyMesai")]
        public IActionResult GetMyMesai()
        {
            var CalisanId = Convert.ToInt32(HttpContext.Request.Cookies["CalisanId"]);

            var list = _resulContext.Mesais.Where(x => x.CalisanId == CalisanId).ToList();

            return Json(list);
        }


        public IActionResult Odemeler() 
        {
            if (!Control())
            {
                 return RedirectToAction("Giris", "Login");
            }

            var kullaniciId = Convert.ToInt32(HttpContext.Request.Cookies["CalisanId"]);
            var liste = _resulContext.Odemelers.Where(y => y.CalisanId == kullaniciId).ToList(); 
            

            return View(liste); 
        }

        public bool Control()
        {
            if (HttpContext.Request.Cookies["Authority"] == "1"  && HttpContext.Request.Cookies["isLogged"] == "true") //calisan ise
            {
                return true;
            }
            else
            {
                return false;
            }


        }
    }
}

Karakoç/Controllers/SefController.cs
using Karakoç.Bussiness.concrete;
using Microsoft.AspNetCore.Mvc;
using ClosedXML.Excel;
using Karakoç.Models;

namespace Karakoç.Controllers
{
    public class SefController : Controller
    {
        private SefManager _sefManager;
        private ResulContext _resulContext;

        public SefController(SefManager sefManager, ResulContext resulContext)
        {
            _sefManager = sefManager;
            _resulContext = resulContext;
        }


        public IActionResult Index() // çalışan sayısı  //Hosgeldiniz
        {

            if (!Control())
            {
                return RedirectToAction("Giris", "Login");
            }

            // Tüm çalışanları al
            var calisanlar = _sefManager.GetCalisansVerify();
            var Aktifcalisanlar = _sefManager.GetCalisansVerifyTrue();


            ViewBag.UserName = HttpContext.Request.Cookies["UserName"];
            ViewBag.UserSurName = HttpContext.Request.Cookies["UserSurName"];

            // Çalışan sayısını ViewBag ile gönder
            ViewBag.CalisanSayisi = calisanlar.Count;
            ViewBag.AktifCalisanSayisi = Aktifcalisanlar.Count;


            return View(); // Çalışanları da model olarak gönder
        }

        public IActionResult ExportCalisan()
        {
            var employees = _resulContext.Calisans.ToList();
            using (var workbook = new XLWorkbook())
            {
                var worksheet = workbook.Worksheets.Add("Çalışanlar");

                // Başlık "Karakoç İnşaat"
                worksheet.Range("C1:G1").Merge().Value = "Karakoç İnşaat";
                worksheet.Range("C1:G1").Style.Font.Bold = true;
                worksheet.Range("C1:G1").Style.Font.FontSize = 16;
                worksheet.Range("C1:G1").Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;

                // Sağ üst köşeye tarih
                worksheet.Cell(2, 7).Value = DateTime.Now.ToString("dd.MM.yyyy");

                // Üçüncü satır boş bırak ve başlıklar
                worksheet.Cell(4, 3).Value = "No";
                worksheet.Cell(4, 4).Value = "TC Kimlik";
                worksheet.Cell(4, 5).Value = "Ad";
                worksheet.Cell(4, 6).Value = "Soyad";
                worksheet.Cell(4, 7).Value = "Durumu";

                // No sütunu genişliği
                worksheet.Column(3).Width = 5;
                worksheet.Column(4).Width = 15;

                // Verileri doldur ve numaralandır
                for (int i = 0, row = 5; i < employees.Count; i++)
                {
                    if (employees[i].Authority == 4) continue;

                    worksheet.Cell(row, 3).Value = row - 4; // No sütunu
                    worksheet.Cell(row, 4).Value = employees[i].TcKimlik;
                    worksheet.Cell(row, 5).Value = employees[i].Name;
                    worksheet.Cell(row, 6).Value = employees[i].Surname;
                    worksheet.Cell(row, 7).Value = employees[i].Verify.HasValue
                                                    ? (employees[i].Verify.Value ? "Çalışıyor" : "Çalışmıyor")
                                                    : "Belirsiz";

                    row++;
                }

                // Tablo oluşturma ve stil
                var tableRange = worksheet.Range(4, 3, employees.Count + 4, 7);
                var table = tableRange.CreateTable();
                table.Theme = XLTableTheme.TableStyleMedium9;

                // Başlıkları ortala ve kalın yap
                var headerRow = worksheet.Range(4, 3, 4, 7);
                headerRow.Style.Font.Bold = true;
                headerRow.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;

                using (var stream = new MemoryStream())
                {
                    workbook.SaveAs(stream);
                    var content = stream.ToArray();
                    return File(content, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Calisanlar.xlsx");
                }
            }
        }
        public async Task<IActionResult> GetYevmiye()
        {
            var yevmiyeler = await _sefManager.GetYevmiyeler();

            var veriler = yevmiyeler.Select(c => new
            {

                c.Tarih,
                c.IsWorked,
                c.IsHalfWorked,
                c.IsWorkedCompany,
                CalisanID = c.CalisanId,
                CalisanAd = c.Calisan.Name,
                CalisanSoyad = c.Calisan.Surname

            }).ToList();

            // Normal olarak view döndür
            return Json(veriler);
        }

        public IActionResult YevmiyeGor()
        {
            if (!Control())
            {
                return RedirectToAction("Giris", "Login");
            }


            return View();
        }


        public IActionResult MesaiGor()
        {
            if (!Control())
            {
                return RedirectToAction("Giris", "Login");
            }


            return View();
        }

        public async Task<IActionResult> GetMesai()
        {
            if (!Control())
            {
                return RedirectToAction("Giris", "Login");
            }


            var yevmiyeler = await _sefManager.GetMesai();

            var veriler = yevmiyeler.Select(c => new
            {

                c.Tarih,
                c.IsWorked,
                c.IsFullWorked,
                c.IsWorkedCompany,
                CalisanID = c.CalisanId,
                CalisanAd = c.Calisan.Name,
                CalisanSoyad = c.Calisan.Surname

            }).ToList();

            // Normal olarak view döndür
            return Json(veriler);
        }



        public IActionResult Ödemeler()
        {
            if (!Control())
            {
                return RedirectToAction("Giris", "Login");
            }


            return View(_sefManager.GetGelir());
        }

        [Route("/Sef/Calisan/{id}")]
        public IActionResult Calisan(int id)
        {
            if (!Control())
            {
                return RedirectToAction("Giris", "Login");
            }

            var calisan = _sefManager.GetCalisanById(id);

            if (calisan == null)
            {
                return NotFound();
            }

            return View(calisan);
        }

        public IActionResult CalisanList()
        {
            if (!Control())
            {
                return RedirectToAction("Giris", "Login");
            }

            return View(_sefManager.GetCalisansVerify());
        }

        public bool Control()
        {
            if (HttpContext.Request.Cookies["Authority"] == "4") //admin veya  mimar ise
            {
                return true;
            }
            else
            {
                return false;
            }
        }

        [HttpGet]
        public IActionResult ExportHakedis(int ay, int yil)
        {
            var calisanlar = _resulContext.Calisans.ToList();
            var yevmiyeler = _resulContext.Yevmiyelers.Where(y => y.Tarih.Value.Year == yil && y.Tarih.Value.Month == ay).ToList();
            var mesailer = _resulContext.Mesais.Where(m => m.Tarih.Year == yil && m.Tarih.Month == ay).ToList();

            using (var workbook = new XLWorkbook())
            {
                DateTime now = DateTime.Now;

                void ApplyCommonStyles(IXLWorksheet sheet)
                {
                    // Başlıklar
                    var titleCell = sheet.Range("A1:AJ1");
                    titleCell.Merge();
                    titleCell.Value = "TURYEM YAPI ALÇI-SIVA PUNTAJ LİSTESİ";
                    titleCell.Style.Font.Bold = true;
                    titleCell.Style.Font.FontSize = 18;
                    titleCell.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;

                    var periodCell = sheet.Range("A2:AJ2");
                    periodCell.Merge();
                    periodCell.Value = $"AİT OLDUĞU ÇALIŞMA DÖNEMİ: {ay}/{yil}";
                    periodCell.Style.Font.FontSize = 18;
                    periodCell.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;

                    // Çalıştığı Günler Başlığı
                    var calistigiGunlerCell = sheet.Range("A3:AJ3");
                    calistigiGunlerCell.Merge();
                    calistigiGunlerCell.Value = "ÇALIŞTIĞI GÜNLER";
                    calistigiGunlerCell.Style.Font.Bold = true;
                    calistigiGunlerCell.Style.Font.FontSize = 18;
                    calistigiGunlerCell.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;

                    // Dosyanın oluşturulma tarihi
                    var dateCell = sheet.Range("AK2:AL2");
                    dateCell.Merge();
                    dateCell.Value = now.ToString("dd.MM.yyyy");
                    dateCell.Style.Font.Bold = true;
                    dateCell.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;

                    // Günlerin olduğu satır
                    sheet.Cell(4, 1).Value = "PERSONELİN ADI SOYADI";
                    sheet.Cell(4, 1).Style.Font.Bold = true;
                    sheet.Cell(4, 1).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                    sheet.Cell(4, 1).Style.Alignment.WrapText = true;

                    sheet.Cell(4, 2).Value = "Görev";
                    sheet.Cell(4, 2).Style.Font.Bold = true;
                    sheet.Cell(4, 2).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;

                    for (int gun = 1; gun <= DateTime.DaysInMonth(yil, ay); gun++)
                    {
                        var cell = sheet.Cell(4, gun + 2);
                        cell.Value = gun;
                        cell.Style.Font.Bold = true;
                        cell.Style.Font.FontSize = 14;
                        cell.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;

Karakoç/Views/Sef/CalisanList.cshtml
@{
    ViewData["Title"] = "CalisanList";
    Layout = "~/Views/Shared/_MimarLayout.cshtml";
}

<main class="main users chart-page" id="skip-target">
    <div class="container">
        <h2 class="main-title">Çalışanların Listesi</h2>

        <table class="table table-bordered table-primary">
            <thead>
                <tr>
                    <th>isim Listesi</th>
                    <th>Kayıt Tarihi</th>
                    <th>Çalışıyor mu?</th>
                    
                </tr>
            </thead>
            <tbody>
                @foreach (var calisan in Model)
                {
                    <tr>
                        <td>
                            <a href="@Url.Action("Calisan","Sef", new { id = calisan.CalısanId })">
                                @calisan.Name @calisan.Surname
                            </a>
                        </td>
                        <td>@calisan.KayıtTarihi?.ToString("dd.MM.yyyy")</td>
                        <td>
                            @if (calisan.Verify != null)
                            {
                                if ((bool)calisan.Verify)
                                {
                                    <a href="#" class="btn btn-success  btn-disabled">Aktif Çalışan</a>
                                }
                                else
                                {
                                    <a href="#" class="btn btn-warning  btn-disabled">Pasif Çalışan</a>
                                }
                            }
                            else
                            {
                                <a href="##" class="btn btn-Danger">!! Hata !!</a>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <br /> <br />
        <a class="btn btn-success" href="~/Sef/ExportCalisan">Excel Olarak İndir</a>
    </div>
</main>

Karakoç/Views/Sef/MesaiGor.cshtml
@{
    ViewData["Title"] = "MesaiGor";
    Layout = "~/Views/Shared/_MimarLayout.cshtml";
}

<!-- jQuery dahil et -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<main class="" id="">
    <div class="">
        <h2 class="main-title">Çalışanların Mesai Bilgisi</h2>

        <!-- Yıl ve Ay seçimi için dropdown menüler -->
        <div style="margin-bottom:20px;">
            <label for="yearSelect" style="color:white;">Yıl Seçin:</label>
            <select id="yearSelect">
                <!-- Yılları doldur -->
                <script>
                    const currentYear = new Date().getFullYear();
                    for (let year = currentYear - 5; year <= currentYear + 1; year++) {
                        $('#yearSelect').append(new Option(year, year));
                    }
                    $('#yearSelect').val(currentYear); // Varsayılan olarak mevcut yılı seç
                </script>
            </select>

            <label for="monthSelect" style="color:white;">Ay Seçin:</label>
            <select id="monthSelect">
                <!-- Ayları doldur -->
                <script>
                    const months = ["Ocak", "Şubat", "Mart", "Nisan", "Mayıs", "Haziran", "Temmuz", "Ağustos", "Eylül", "Ekim", "Kasım", "Aralık"];
                    months.forEach((month, index) => {
                        $('#monthSelect').append(new Option(month, index + 1));
                    });
                    $('#monthSelect').val(new Date().getMonth() + 1); // Varsayılan olarak mevcut ayı seç
                </script>
            </select>
        </div>

        <!-- Tablo alanı -->
        <div id="tableContainer"></div>
    </div>
</main>

<script>
    $(document).ready(function () {
        let allData = []; // Tüm verileri burada tutacağız

        // Verileri al
        $.ajax({
            url: '@Url.Action("GetMesai", "Sef")', // Controller ve action'ı ayarlayın
            type: 'GET',
            success: function (data) {
                allData = data.$values || [];
                updateTable(); // Başlangıçta tabloyu oluştur
            },
            error: function (xhr, status, error) {
                console.error("Veriler alınırken hata oluştu:", error);
            }
        });

        // Yıl veya Ay değiştirildiğinde tabloyu güncelle
        $('#yearSelect, #monthSelect').change(updateTable);

        // Tabloyu oluşturma fonksiyonu
        function updateTable() {
            const selectedYear = parseInt($('#yearSelect').val());
            const selectedMonth = parseInt($('#monthSelect').val());
            createTable(selectedYear, selectedMonth);
        }

        // Tablo oluşturma fonksiyonu
        function createTable(year, month) {
            const günSayısı = new Date(year, month, 0).getDate(); // Seçilen ayın gün sayısını al
            let tableHtml = `<table class="table table-bordered table-primary">
                                            <thead>
                                                <tr>
                                                    <th>Çalışan</th>`;
            for (let i = 1; i <= günSayısı; i++) {
                tableHtml += `<th>${i}</th>`; // Gün başlıkları
            }
            tableHtml += `   </tr>
                                        </thead>
                                        <tbody>`;

            // Çalışan grupları oluştur
            const groupedData = groupDataByEmployee(allData, year, month);
            $.each(groupedData, function (calisan, yevmiyeData) {
                tableHtml += `<tr><td>${calisan}</td>`;

                for (let day = 1; day <= günSayısı; day++) {
                    const isWorked = yevmiyeData[day] && yevmiyeData[day].isWorked;
                    const isFullWorked = yevmiyeData[day] && yevmiyeData[day].isFullWorked;
                    const isWorkedCompany = yevmiyeData[day] && yevmiyeData[day].isWorkedCompany;

                    if (isFullWorked === true) {
                        tableHtml += `<td style="background-color: ${isFullWorked ? "blue" : "transparent"}"></td>`;
                    }
                    else if (isWorkedCompany === true) {
                        tableHtml += `<td style="background-color: ${isWorkedCompany ? "green" : "transparent"}"></td>`;
                    }
                    else if (isWorked === true) {
                        tableHtml += `<td style="background-color: ${isWorked ? "green" : "transparent"}"></td>`;
                    } else {
                        tableHtml += `<td style="background-color: ${isWorked ? "green" : "transparent"}"></td>`;
                    }
                    
                }
                tableHtml += `</tr>`;
            });

            tableHtml += `</tbody></table>`;
            $('#tableContainer').html(tableHtml); // Tabloyu sayfaya ekle
        }

        // Verileri çalışana göre gruplama fonksiyonu
        function groupDataByEmployee(data, year, month) {
            const grouped = {};
            data.forEach(item => {
                const date = new Date(item.tarih);
                const calisan = item.calisanAd + " " + item.calisanSoyad;

                if (date.getFullYear() === year && date.getMonth() + 1 === month) {
                    if (!grouped[calisan]) grouped[calisan] = {};
                    grouped[calisan][date.getDate()] = {
                        
                        
                        isWorked: item.isWorked,
                        isFullWorked: item.isFullWorked,
                        isWorkedCompany: item.isWorkedCompany

                    };
                }
            });
            return grouped;
        }
    });
</script>

Karakoç/Views/Sef/YevmiyeGor.cshtml
@model List<Karakoç.Models.Yevmiyeler>
@{
    ViewData["Title"] = "YevmiyeGor";
    Layout = "~/Views/Shared/_MimarLayout.cshtml";
}

<!-- jQuery dahil et -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<main class="" id="">

    <div class="">
        <h2 class="main-title">Çalışanların Yevmiye Bilgisi</h2>

        <!-- Yıl ve Ay seçimi için dropdown menüler -->
        <div style="margin-bottom:20px;">
            <label for="yearSelect" style="color:white;">Yıl Seçin:</label>
            <select id="yearSelect">
                <!-- Yılları doldur -->
                <script>
                    const currentYear = new Date().getFullYear();
                    for (let year = currentYear - 5; year <= currentYear + 1; year++) {
                        $('#yearSelect').append(new Option(year, year));
                    }
                    $('#yearSelect').val(currentYear); // Varsayılan olarak mevcut yılı seç
                </script>
            </select>

            <label for="monthSelect" style="color:white;">Ay Seçin:</label>
            <select id="monthSelect">
                <!-- Ayları doldur -->
                <script>
                    const months = ["Ocak", "Şubat", "Mart", "Nisan", "Mayıs", "Haziran", "Temmuz", "Ağustos", "Eylül", "Ekim", "Kasım", "Aralık"];
                    months.forEach((month, index) => {
                        $('#monthSelect').append(new Option(month, index + 1));
                    });
                    $('#monthSelect').val(new Date().getMonth() + 1); // Varsayılan olarak mevcut ayı seç
                </script>
            </select>
        </div>

        <!-- Tablo alanı -->
        <div id="tableContainer"></div>
    </div>

    <!-- Link buttonunun href kısmını dinamik hale getirme -->
    <a id="exportLink" class="btn btn-success" href="#">Excel Olarak İndir</a>

</main>



<script>
    // Sayfa yüklendiğinde seçilen yıl ve ayı kontrol et ve linki güncelle
    function updateExportLink() {
        const selectedYear = $('#yearSelect').val();
        const selectedMonth = $('#monthSelect').val();

        // Excel linkini dinamik olarak oluştur
        const exportLink = `ExportHakedis?ay=${selectedMonth}&yil=${selectedYear}`;
        $('#exportLink').attr('href', exportLink);
    }

    // Dropdown menülerde değişiklik olduğunda linki güncelle
    $('#yearSelect, #monthSelect').change(function () {
        updateExportLink();
    });

    // Sayfa yüklendiğinde linki ilk defa güncelle
    updateExportLink();
</script>


<script>
    $(document).ready(function () {
        let allData = []; // Tüm verileri burada tutacağız

        // Verileri al
        $.ajax({
            url: '@Url.Action("GetYevmiye", "Sef")', // Controller ve action'ı ayarlayın
            type: 'GET',
            success: function (data) {
                allData = data.$values || [];
                updateTable(); // Başlangıçta tabloyu oluştur
            },
            error: function (xhr, status, error) {
                console.error("Veriler alınırken hata oluştu:", error);
            }
        });

        // Yıl veya Ay değiştirildiğinde tabloyu güncelle
        $('#yearSelect, #monthSelect').change(updateTable);

        // Tabloyu güncelleme fonksiyonu
        function updateTable() {
            const selectedYear = parseInt($('#yearSelect').val());
            const selectedMonth = parseInt($('#monthSelect').val());
            createTable(selectedYear, selectedMonth);
        }

        // Tablo oluşturma fonksiyonu
        function createTable(year, month) {
            const günSayısı = new Date(year, month, 0).getDate(); // Seçilen ayın gün sayısını al
            let tableHtml = `<table class="table table-bordered table-primary">
                                                            <thead>
                                                                <tr>
                                                                    <th>Çalışan</th>`;
            for (let i = 1; i <= günSayısı; i++) {
                tableHtml += `<th>${i}</th>`; // Gün başlıkları
            }
            tableHtml += `   </tr>
                                                        </thead>
                                                        <tbody>`;

            // Çalışan grupları oluştur
            const groupedData = groupDataByEmployee(allData, year, month);
            $.each(groupedData, function (calisan, yevmiyeData) {
                tableHtml += `<tr><td>${calisan}</td>`;

                for (let day = 1; day <= günSayısı; day++) {
                    const isWorked = yevmiyeData[day] && yevmiyeData[day].isWorked;
                    const isHalfWorked = yevmiyeData[day] && yevmiyeData[day].isHalfWorked;
                    const isWorkedCompany = yevmiyeData[day] && yevmiyeData[day].isWorkedCompany;

                    // Her durumda mavi yapmak için sadece bir koşul yazıyoruz
                    if (isWorkedCompany || isWorked || isHalfWorked) {
                        tableHtml += `<td style="background-color: blue;"></td>`;
                    } else {
                        tableHtml += `<td></td>`; // Hiçbir durum gerçekleşmezse boş hücre
                    }
                }

                tableHtml += `</tr>`;
            });

            tableHtml += `</tbody></table>`;
            $('#tableContainer').html(tableHtml); // Tabloyu sayfaya ekle
        }

        // Verileri çalışana göre gruplama fonksiyonu
        function groupDataByEmployee(data, year, month) {
            const grouped = {};
            data.forEach(item => {
                const date = new Date(item.tarih);
                const calisan = item.calisanAd + " " + item.calisanSoyad;

                if (date.getFullYear() === year && date.getMonth() + 1 === month) {
                    if (!grouped[calisan]) grouped[calisan] = {};
                    //
                    // Hem tam çalışma hem yarım çalışma bilgilerini ekle
                    grouped[calisan][date.getDate()] = {
                        isWorked: item.isWorked,
                        isHalfWorked: item.isHalfWorked,
                        isWorkedCompany: item.isWorkedCompany
                    };
                }
            });
            return grouped;
        }
    });
</script>